version: 1.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:sa-east-1:274201610284:task-definition/auth-td:1"
        LoadBalancerInfo:
          ContainerName: "auth-container"
          ContainerPort: "9095"
        PlatformVersion: "LATEST"